stages:
  - build
  - test
  - deploy

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: "true"

backend-build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - cd WealthWeaver/BankingService
    - dotnet restore
    - dotnet build --no-restore
  artifacts:
    paths:
      - WealthWeaver/BankingService/bin/

backend-test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - cd WealthWeaver/BankingService
    - dotnet test

frontend-build:
  stage: build
  image: node:latest
  script:
    - cd WealthWeaverFrontend
    - npm ci
    - npm run build
  artifacts:
    paths:
      - WealthWeaverFrontend/build/

frontend-test:
  stage: test
  image: node:latest
  script:
    - cd WealthWeaverFrontend
    - npm ci
    - npm test

deploy:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  only:
    - main
