name: Build-And-Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-backend:
    name: Build and Test Backend
    runs-on: windows-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore NuGet packages
      run: |
        cd WealthWeaver
        nuget restore WealthWeaver.sln
    
    - name: Build Backend
      run: |
        cd WealthWeaver
        msbuild /p:Configuration=Release
    
    - name: Test Backend
      run: |
        cd WealthWeaver
        dotnet test --no-build --verbosity normal

  build-and-test-frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install Frontend Dependencies
      run: |
        cd WealthWeaverFrontend
        npm ci
    
    - name: Build Frontend
      run: |
        cd WealthWeaverFrontend
        npm run build
    
    - name: Test Frontend
      run: |
        cd WealthWeaverFrontend
        npm test
